# Generated by Django 2.0.7 on 2018-07-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0003_auto_20180725_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='my',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='my',
            name='title',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
