# Generated by Django 2.0.7 on 2018-07-29 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0007_comment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('firstName', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='userImage',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Profiles'),
        ),
        migrations.AddField(
            model_name='myfriends',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Profiles'),
        ),
    ]
