# Generated by Django 2.0.7 on 2018-07-29 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0011_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Profiles')),
            ],
        ),
    ]
