# Generated by Django 2.0.7 on 2018-07-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0013_auto_20180729_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail.Profiles')),
            ],
        ),
        migrations.RemoveField(
            model_name='myfriends',
            name='friends',
        ),
        migrations.DeleteModel(
            name='MyFriends',
        ),
    ]
