# Generated by Django 2.0.7 on 2018-07-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0014_auto_20180729_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hi',
            name='friends',
        ),
    ]
