# Generated by Django 2.0.7 on 2018-07-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0017_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[('Mr', 'Ms'), ('Mrs', 'Mrs')], max_length=20)),
            ],
        ),
    ]
