# Generated by Django 2.0.7 on 2018-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0019_auto_20180731_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='wrong',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
