# Generated by Django 2.0.7 on 2018-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0020_test_wrong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.CharField(max_length=100)),
                ('wrong', models.CharField(max_length=100)),
                ('username1', models.CharField(max_length=100)),
                ('username2', models.CharField(max_length=100)),
            ],
        ),
    ]
