# Generated by Django 2.0.7 on 2018-07-31 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0021_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='wrong',
        ),
    ]
